name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always



jobs:
  strategy:
    matrix:
      handling-strategy: [client-handler, proxy]
  
  build:

    runs-on: ubuntu-latest
    env:
      HANDLING_STRATEGY: matrix.handling-strategy

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Clippy
      run: cargo clippy --verbose
    - name: Check formatting
      run: cargo fmt --check
    - name: Run tests
      run: cargo test --verbose
